apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tidus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tidus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tidus.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "tidus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tidus.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
