"""add_model_price_snapshots

Revision ID: a94b761a5d86
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 06:50:05.309457

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a94b761a5d86'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_price_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('input_usd_1m', sa.Float(), nullable=False),
    sa.Column('output_usd_1m', sa.Float(), nullable=False),
    sa.Column('cache_read_usd_1m', sa.Float(), nullable=False),
    sa.Column('cache_write_usd_1m', sa.Float(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['model_catalog_revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'snapshot_date', name='uq_model_price_snapshot')
    )
    op.create_index('ix_model_price_snapshots_date', 'model_price_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_model_price_snapshots_model_date', 'model_price_snapshots', ['model_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_price_market_history_model_id'), 'price_market_history', ['model_id'], unique=False)
    op.create_index(op.f('ix_price_market_history_revision_id'), 'price_market_history', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_market_history_revision_id'), table_name='price_market_history')
    op.drop_index(op.f('ix_price_market_history_model_id'), table_name='price_market_history')
    op.drop_index('ix_model_price_snapshots_model_date', table_name='model_price_snapshots')
    op.drop_index('ix_model_price_snapshots_date', table_name='model_price_snapshots')
    op.drop_table('model_price_snapshots')
    # ### end Alembic commands ###
