subscribers:
- active: true
  email: kenologist.wong@gmail.com
  name: Kenny Wong
  subscribed_at: '2026-04-09'
- active: true
  email: lapkei01@gmail.com
  name: Kenny Wong
  subscribed_at: '2026-04-10'
