"""tidus-setup — Interactive first-run configuration wizard.

Detects available API keys, sets up a team budget, tests vendor connectivity,
and prints a ready-to-use curl command so the user can see savings in minutes.

Usage:
    tidus-setup                  # Interactive (prompts for team name + budget)
    tidus-setup --defaults       # Non-interactive (uses all defaults, great for Docker)
    tidus-setup --skip-checks    # Skip vendor connectivity checks (faster)

The wizard NEVER overwrites an existing config/budgets.yaml — it only creates
one if the file is absent. To re-run setup, delete config/budgets.yaml first.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

# ── Colours (ANSI) ────────────────────────────────────────────────────────────
_GREEN  = "\033[92m"
_YELLOW = "\033[93m"
_RED    = "\033[91m"
_CYAN   = "\033[96m"
_BOLD   = "\033[1m"
_DIM    = "\033[2m"
_RESET  = "\033[0m"

# Windows cmd.exe does not support ANSI by default
if sys.platform == "win32":
    try:
        import ctypes
        ctypes.windll.kernel32.SetConsoleMode(
            ctypes.windll.kernel32.GetStdHandle(-11), 7
        )
    except Exception:
        _GREEN = _YELLOW = _RED = _CYAN = _BOLD = _DIM = _RESET = ""


def _ok(msg: str) -> str:  return f"  {_GREEN}✓{_RESET} {msg}"
def _warn(msg: str) -> str: return f"  {_YELLOW}○{_RESET} {msg}"
def _fail(msg: str) -> str: return f"  {_RED}✗{_RESET} {msg}"


# ── Vendor key → display name mapping ────────────────────────────────────────

_VENDORS = [
    ("ANTHROPIC_API_KEY",  "anthropic",  "Claude (Opus / Sonnet / Haiku)"),
    ("OPENAI_API_KEY",     "openai",     "GPT-4o / GPT-4o-mini"),
    ("GOOGLE_API_KEY",     "google",     "Gemini Pro / Flash"),
    ("MISTRAL_API_KEY",    "mistral",    "Mistral / Codestral"),
    ("DEEPSEEK_API_KEY",   "deepseek",   "DeepSeek R1 / V3"),
    ("XAI_API_KEY",        "xai",        "Grok 3"),
    ("MOONSHOT_API_KEY",   "moonshot",   "Kimi K2.5"),
]


# ── .env loader ───────────────────────────────────────────────────────────────

def _load_dotenv(env_path: Path = Path(".env")) -> None:
    """Minimal .env loader — does not overwrite already-set env vars."""
    if not env_path.exists():
        return
    with env_path.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val


# ── Budget YAML writer ────────────────────────────────────────────────────────

def _write_budgets_yaml(team_name: str, limit_usd: float, config_dir: Path) -> Path:
    config_dir.mkdir(parents=True, exist_ok=True)
    budgets_path = config_dir / "budgets.yaml"
    content = f"""\
# Tidus Budget Policies — generated by tidus-setup
# Edit this file to adjust limits, add teams, or change periods.

budgets:

  - policy_id: "{team_name}-monthly"
    scope: team
    scope_id: "{team_name}"
    period: monthly
    limit_usd: {limit_usd:.2f}
    warn_at_pct: 0.80
    hard_stop: true
"""
    budgets_path.write_text(content, encoding="utf-8")
    return budgets_path


# ── Connectivity check ────────────────────────────────────────────────────────

async def _check_ollama(base_url: str) -> bool:
    """Return True if Ollama is reachable."""
    try:
        import httpx
        async with httpx.AsyncClient(timeout=3.0) as client:
            r = await client.get(f"{base_url}/api/tags")
            return r.status_code == 200
    except Exception:
        return False


async def _check_vendor(vendor: str) -> tuple[bool, float]:
    """Quick adapter health check. Returns (is_healthy, latency_ms)."""
    try:
        import time
        from tidus.adapters.adapter_factory import get_adapter
        adapter = get_adapter(vendor)
        start = time.monotonic()
        ok = await adapter.health_check(None)
        ms = (time.monotonic() - start) * 1000
        return ok, round(ms, 0)
    except Exception:
        return False, 0.0


# ── Input helpers ─────────────────────────────────────────────────────────────

def _prompt(msg: str, default: str) -> str:
    try:
        answer = input(f"  {msg} [{default}]: ").strip()
        return answer if answer else default
    except (EOFError, KeyboardInterrupt):
        return default


# ── Main wizard ───────────────────────────────────────────────────────────────

async def _run_wizard(defaults: bool, skip_checks: bool) -> None:
    print()
    print(f"{_BOLD}{_CYAN}Welcome to Tidus v1.0.0 — Enterprise AI Router{_RESET}")
    print("=" * 52)
    print()

    # ── Step 1: Detect API keys ───────────────────────────────────────────────
    print(f"{_BOLD}[Step 1/4] Detecting API keys…{_RESET}")
    _load_dotenv()

    active_vendors: list[str] = []
    for env_key, vendor_id, label in _VENDORS:
        if os.environ.get(env_key, "").strip():
            print(_ok(f"{env_key} found — {label}"))
            active_vendors.append(vendor_id)
        else:
            print(_warn(f"{env_key} not set — {label} disabled"))

    ollama_url = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
    ollama_ok = await _check_ollama(ollama_url)
    if ollama_ok:
        print(_ok(f"Ollama reachable at {ollama_url} — local models enabled"))
        active_vendors.append("ollama")
    else:
        print(_warn(f"Ollama not running at {ollama_url} — local models disabled"))

    if not active_vendors:
        print()
        print(f"  {_RED}No vendors configured.{_RESET} Add at least one API key to .env")
        print("  Example: ANTHROPIC_API_KEY=sk-ant-...")
        print()
        sys.exit(1)

    print()

    # ── Step 2: Team budget setup ─────────────────────────────────────────────
    print(f"{_BOLD}[Step 2/4] Setting up your first team budget…{_RESET}")

    config_dir = Path("config")
    budgets_path = config_dir / "budgets.yaml"

    if budgets_path.exists():
        print(_ok(f"config/budgets.yaml already exists — skipping (delete it to reconfigure)"))
        team_name = "team-default"
        limit_usd = 500.0
    else:
        if defaults:
            team_name = "team-default"
            limit_usd = 500.0
        else:
            team_name = _prompt("Team name", "team-default")
            try:
                limit_str = _prompt("Monthly spend limit in USD", "500")
                limit_usd = float(limit_str)
            except ValueError:
                limit_usd = 500.0

        _write_budgets_yaml(team_name, limit_usd, config_dir)
        print(_ok(f"Written to config/budgets.yaml  (team={team_name}, limit=${limit_usd:.2f}/month)"))

    print()

    # ── Step 3: Vendor connectivity ───────────────────────────────────────────
    print(f"{_BOLD}[Step 3/4] Testing vendor connectivity…{_RESET}")

    if skip_checks:
        print(_warn("Skipped (--skip-checks)"))
    else:
        for env_key, vendor_id, label in _VENDORS:
            if vendor_id not in active_vendors:
                continue
            ok, ms = await _check_vendor(vendor_id)
            if ok:
                print(_ok(f"{label}: healthy ({ms:.0f} ms)"))
            else:
                print(_warn(f"{label}: check failed (API key may be invalid or service down)"))

    print()

    # ── Step 4: Summary ───────────────────────────────────────────────────────
    print(f"{_BOLD}[Step 4/4] Ready!{_RESET}")
    print()
    print(f"  {_GREEN}Start Tidus:{_RESET}")
    print( "    uvicorn tidus.main:app --reload")
    print()
    print(f"  {_GREEN}Open the dashboard:{_RESET}")
    print( "    http://localhost:8000/dashboard/")
    print()
    print(f"  {_GREEN}Send your first request:{_RESET}")
    print(f'    curl -s -X POST http://localhost:8000/api/v1/complete \\')
    print(f'      -H "Content-Type: application/json" \\')
    print(f'      -d \'{{"team_id":"{team_name}","complexity":"simple","domain":"chat",')
    print( '           "estimated_input_tokens":500,')
    print( '           "messages":[{"role":"user","content":"Hello!"}]}}\'')
    print()
    print(f"  {_GREEN}See your savings report:{_RESET}")
    print( "    curl http://localhost:8000/api/v1/reports/monthly | python -m json.tool")
    print()
    print(f"{_DIM}Tip: after a few requests open the dashboard to see the savings panel light up.{_RESET}")
    print()


def main() -> None:
    """CLI entry point: tidus-setup"""
    parser = argparse.ArgumentParser(
        prog="tidus-setup",
        description="Tidus first-run configuration wizard",
    )
    parser.add_argument(
        "--defaults",
        action="store_true",
        help="Non-interactive mode — use all default values (good for Docker / CI)",
    )
    parser.add_argument(
        "--skip-checks",
        action="store_true",
        help="Skip vendor connectivity tests (faster)",
    )
    args = parser.parse_args()

    asyncio.run(_run_wizard(defaults=args.defaults, skip_checks=args.skip_checks))


if __name__ == "__main__":
    main()
